# Generated by Django 4.0.2 on 2022-03-11 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contato',
            old_name='data_criacai',
            new_name='data_criacao',
        ),
    ]
